name: HACS

on:
  push:
  pull_request:
  release:
    types:
      - published
  schedule:
    - cron: "22 0 * * 0"
      timezone: America/Detroit
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    name: Validate HACS repository
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
