name: Hassfest

on:
  push:
  pull_request:
  release:
    types:
      - published
  schedule:
    - cron: "0 9 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
